resize
biometricITC/Fingerprint-Toolbox pull request #41
Opened 2020-12-01 14:08 UTC by woodbe

This is to close #32 if that is accepted.

2020-12-01 21:33 UTC, gfiumara approved these changes

2020-12-02 15:28 UTC, gfiumara requested changes
@woodbe I think the merge to update accidentally reverted the change.

2020-12-02 15:34 UTC, woodbe commented
I was trying to resolve conflicts (to make it easier to merge later), and that showed on one very long line, so I missed it when trying to catch the change.

2020-12-02 15:39 UTC, gfiumara approved these changes

2020-12-03 05:47 UTC, n-kai approved these changes

2020-12-03 13:35 UTC, merged