CSM 2/3 Relief description
biometricITC/Fingerprint-Toolbox pull request #58
Opened 2021-02-08 16:20 UTC by woodbe

CSM 2: ”. The thicker copper traces provide greater relief between the PAI ridges and valleys. - greater relief" - This statement seems not fully understood and suggest to provide better clarification.

Proposal: Does greater mean the higher degree of depth between the ridges and valley ?

CSM 3: "However, the relief between the PAI ridges and valleys will be much smaller than with PCBs" - This statement seems not fully understood and suggest to provide better clarification.

Proposal: Does smaller mean the lower degree of depth between the ridges and valley ?

From spreadsheet (combined due to common topic)

2021-02-09 23:38 UTC, n-kai requested changes
I think that "be" is missing.
a smaller relief (a lower degree of depth) between the PAI ridges and valleys will **be** generated than with PCBs.

2021-02-10 12:07 UTC, gfiumara requested changes

2021-02-10 12:07 UTC, gfiumara commented on FINGERPRINT_Toolbox_Overview.adoc
> +Printed circuit boards come in varying substrate and copper cladding thicknesses. The substrate thickness should be thick enough to allow easy handling and prevent noticeable flexing of the PCB. A th
```suggestion
Printed circuit boards come in varying substrate and copper cladding thicknesses. The substrate thickness should be thick enough to allow easy handling and prevent noticeable flexing of the PCB. A thickness of 1.6 mm is typical and sufficient for PAD testing applications. A common substrate material used in PCBs is designated FR4 or fiberglass reinforced epoxy. The copper cladding should be 2.74 mils thick, referred to as “2 oz. of copper” in the PCB manufacturing industry. This is twice the standard PCB trace thickness of “1 oz. of copper”. The thicker copper traces provide greater relief (i.e., a higher degree of depth) between the PAI ridges and valleys.
```

2021-02-10 12:07 UTC, gfiumara commented on FINGERPRINT_Toolbox_Overview.adoc
> +Molds made from laser-printed overhead transparency material are similar to PCB molds. They are easier, cheaper, and faster to make than PCB molds. However, a smaller relief (a lower degree of depth)
```suggestion
Molds made from laser-printed overhead transparency material are similar to PCB molds. They are easier, cheaper, and faster to make than PCB molds. However, a smaller relief (i.e., a lower degree of depth) between the PAI ridges and valleys will generated than with PCBs.
```

2021-02-10 12:07 UTC, gfiumara commented on FINGERPRINT_Toolbox_Overview.adoc
> +Molds made from laser-printed overhead transparency material are similar to PCB molds. They are easier, cheaper, and faster to make than PCB molds. However, a smaller relief (a lower degree of depth)
```suggestion
Molds made from laser-printed overhead transparency material are similar to PCB molds. They are easier, cheaper, and faster to make than PCB molds. However, a smaller relief (a lower degree of depth) between the PAI ridges and valleys will be generated than with PCBs.
```

2021-02-10 12:07 UTC, gfiumara commented on FINGERPRINT_Toolbox_Overview.adoc
> +Printed circuit boards come in varying substrate and copper cladding thicknesses. The substrate thickness should be thick enough to allow easy handling and prevent noticeable flexing of the PCB. A th
To match **a** smaller relief.

```suggestion
Printed circuit boards come in varying substrate and copper cladding thicknesses. The substrate thickness should be thick enough to allow easy handling and prevent noticeable flexing of the PCB. A thickness of 1.6 mm is typical and sufficient for PAD testing applications. A common substrate material used in PCBs is designated FR4 or fiberglass reinforced epoxy. The copper cladding should be 2.74 mils thick, referred to as “2 oz. of copper” in the PCB manufacturing industry. This is twice the standard PCB trace thickness of “1 oz. of copper”. The thicker copper traces provide a greater relief (a higher degree of depth) between the PAI ridges and valleys.
```

2021-02-10 19:29 UTC, gfiumara commented on FINGERPRINT_Toolbox_Overview.adoc
> +Molds made from laser-printed overhead transparency material are similar to PCB molds. They are easier, cheaper, and faster to make than PCB molds. However, a smaller relief (i.e., a lower degree of
Upon re-reading of this sentence, something isn't quite right. Maybe:

```suggestion
Molds made from laser-printed overhead transparency material are similar to PCB molds. They are easier, cheaper, and faster to make than PCB molds. However, a smaller relief (i.e., a lower degree of depth) between the PAI ridges and valleys will be created.
```

or

```suggestion
Molds made from laser-printed overhead transparency material are similar to PCB molds. They are easier, cheaper, and faster to make than PCB molds. However, a smaller relief (i.e., a lower degree of depth) between the PAI ridges and valleys will be noticed when compared to equivalent PCB molds.
```

2021-02-10 19:40 UTC, woodbe commented
@gfiumara I'm going to punt making this choice to the call tomorrow

2021-02-10 19:59 UTC, gfiumara commented
> @gfiumara I'm going to punt making this choice to the call tomorrow

Sounds good. I have my standard every-other-Thursday 9:30-11 conflict, but I'm fine with anything and would approve the PR after any similar change.

2021-02-11 15:14 UTC, merged