CSM 9/10 dental -> direct
biometricITC/Fingerprint-Toolbox pull request #64
Opened 2021-02-08 17:57 UTC by woodbe

CSM 9: Curved PAI mold preparation

Proposal: As there can be more materials for mold in the future, suggest to put it as general as the preparation of cast.

CSM 10: Dental Impression Material

Proposal: As there can be more materials for mold in the future, suggest to put Dental Impression in the Fingerprint Toolbox Inventory instead in the Fingerprint Toolbox Overview

From spreadsheet

2021-02-08 17:58 UTC, woodbe commented
I have combined these by making the dental impression an example in the overview and using "direct" in the example itself.

2021-02-10 00:37 UTC, n-kai requested changes
The term "Dental impression materials" is also used in other sections like 2.2.1.1.1 and 2.2.2.1.1. They should also be changed.

2021-02-10 19:31 UTC, gfiumara approved these changes

2021-02-10 19:31 UTC, gfiumara commented on FINGERPRINT_Toolbox_Overview.adoc
> +A mold is made from the target finger friction ridge pattern using a direct impression material (such as a direct impression material). The friction ridges of the enrolled finger are pressed into imp
```suggestion
A mold is made from the target finger friction ridge pattern using a direct impression material (such as a dental impression material). The friction ridges of the enrolled finger are pressed into impression material to create a curved mold of the fingerprint.
```

2021-02-11 02:19 UTC, n-kai requested changes
It's better to change L147

a direct impression material (such as a direct impression material)
->
a direct impression material (such as a **dental** impression material)

2021-02-11 15:22 UTC, merged